name: Update snake animation

on:
  schedule:
    - cron: "* */12 * * *"
  workflow_dispatch:

permissions:
  actions: write
  checks: write
  contents: write
  packages: write
  pages: write
  pull-requests: write

jobs:
  build:
    name: Update snake animation
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v2
        with:
          github_user_name: aleach
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9

      - uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: snake
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}